if(EXISTS "/Users/amitpeer/Documents/Code/nx/build-release/tests/integration_tests[1]_tests.cmake")
  include("/Users/amitpeer/Documents/Code/nx/build-release/tests/integration_tests[1]_tests.cmake")
else()
  add_test(integration_tests_NOT_BUILT integration_tests_NOT_BUILT)
endif()
