name: Bug Report
description: File a bug report to help us improve nx
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 
        Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: input
    id: version
    attributes:
      label: nx Version
      description: What version of nx are you running?
      placeholder: "v1.0.0 or commit hash"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux (Ubuntu/Debian)
        - Linux (Arch/Manjaro)
        - Linux (RHEL/CentOS/Fedora)
        - Linux (Other)
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Windows 10
        - Windows 11
        - Other
    validations:
      required: true

  - type: input
    id: terminal
    attributes:
      label: Terminal/Shell
      description: What terminal and shell are you using?
      placeholder: "e.g., Terminal.app with zsh, iTerm2 with bash, Windows Terminal with PowerShell"

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the bug
      placeholder: |
        1. Run command `nx ...`
        2. Do action '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened, including any error messages
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs/Output
      description: |
        Please paste any relevant log output or error messages.
        This will be automatically formatted as code, so no need for backticks.
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here.
        - Screenshots (if applicable)
        - Related issues
        - Workarounds you've tried
        - Any other relevant information

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched the existing issues and this is not a duplicate
          required: true
        - label: I have provided all the requested information
          required: true
        - label: I have tested this with the latest version of nx
          required: true