# Quick Start: nx Git Sync Configuration
# Save as ~/.config/nx/config.toml

# ====================
# QUICK SETUP (3 steps)
# ====================

# 1. CREATE GITHUB REPO:
#    - Go to github.com → New repository → "my-notes" (PRIVATE)
#    - Copy the SSH URL (looks like: git@github.com:username/my-notes.git)

# 2. PASTE YOUR INFO:
sync = "git"
git_remote = "PASTE_YOUR_REPO_URL_HERE"  # ← Change this!
git_user_name = "Your Name"              # ← Change this!
git_user_email = "your@email.com"        # ← Change this!

# 3. ENABLE AUTO-SYNC:
[auto_sync]
enabled = true

# ====================
# AFTER SAVING CONFIG
# ====================

# First time setup (run ONE command):
#   nx sync init     # If you have existing notes
#   nx sync clone    # If downloading existing notes

# That's it! Your notes will now sync automatically across devices.

# ====================
# AUTHENTICATION HELP
# ====================

# If you get "Permission denied" errors:
# 1. ssh-keygen -t ed25519 -C "your@email.com"
# 2. cat ~/.ssh/id_ed25519.pub  # Copy this
# 3. GitHub → Settings → SSH Keys → Add New
# 4. Test: ssh -T git@github.com

# ====================
# OPTIONAL SETTINGS
# ====================

notes_dir = "~/Documents/notes"
editor = "code"  # or "nvim", "vim", "nano"

[auto_sync]
auto_push_delay_seconds = 300    # Wait 5 min before pushing
sync_interval_seconds = 1800     # Background sync every 30 min
conflict_strategy = "manual"     # How to handle conflicts