# Example nx configuration with automatic Git synchronization
# Save this as ~/.config/nx/config.toml

# Basic configuration
notes_dir = "~/Documents/notes"
editor = "nvim"

# ============================================================================
# GIT SYNCHRONIZATION SETUP
# ============================================================================

# Enable Git sync (required for multi-device sync)
sync = "git"

# STEP 1: Create a private Git repository
# - Go to GitHub/GitLab/Gitea and create a new PRIVATE repository
# - Name it something like "my-notes" or "personal-notes"
# - Copy the SSH or HTTPS URL

# STEP 2: Set your Git remote URL
# SSH (recommended - no password needed after setup):
git_remote = "git@github.com:yourusername/my-notes.git"
# OR HTTPS (requires username/password or token):
# git_remote = "https://github.com/yourusername/my-notes.git"

# STEP 3: Configure Git identity
git_user_name = "Your Full Name"
git_user_email = "your.email@example.com"

# STEP 4: After saving this config, run ONE of these commands:
# 
# For NEW notes (create repo from existing notes):
#   nx sync init
#
# For EXISTING repo (download existing notes):
#   nx sync clone
#
# STEP 5: Test the setup:
#   nx sync status    # Check sync status
#   nx sync sync      # Manual sync test

# ============================================================================
# AUTHENTICATION SETUP (Important!)
# ============================================================================

# For SSH (git@github.com URLs):
# 1. Generate SSH key: ssh-keygen -t ed25519 -C "your.email@example.com"
# 2. Add to SSH agent: ssh-add ~/.ssh/id_ed25519
# 3. Copy public key: cat ~/.ssh/id_ed25519.pub
# 4. Add to GitHub: Settings > SSH and GPG keys > New SSH key
# 5. Test: ssh -T git@github.com

# For HTTPS (https://github.com URLs):
# 1. Create Personal Access Token on GitHub
# 2. Git will prompt for username (your GitHub username)
# 3. Use token as password (not your GitHub password)
# 4. Consider using git credential manager for convenience

# TROUBLESHOOTING:
# - Permission denied: Check SSH key setup
# - Repository not found: Verify git_remote URL and repository exists
# - Authentication failed: Check credentials or SSH key
# - Run: nx doctor --category git  # For detailed diagnostics

# Automatic sync configuration
[auto_sync]
# Enable automatic synchronization
enabled = true

# Pull remote changes when nx starts (any command)
auto_pull_on_startup = true

# Automatically push changes after note operations
auto_push_on_changes = true

# Wait 5 minutes after last change before pushing (batches changes)
auto_push_delay_seconds = 300

# Background sync every 30 minutes
sync_interval_seconds = 1800

# How to handle conflicts:
# - "manual": Prompt user (default, most safe)
# - "ours": Keep local changes
# - "theirs": Accept remote changes  
# - "smart": AI-assisted resolution (future)
conflict_strategy = "manual"

# Maximum auto-resolution attempts before falling back to manual
max_auto_resolve_attempts = 3

# Sync all changes before app shutdown
sync_on_shutdown = true

# Show sync status in TUI status bar
show_sync_status = true

# AI configuration (optional)
[ai]
provider = "openai"
model = "gpt-4"
api_key = "env:OPENAI_API_KEY"